#!/usr/bin/env python3
"""
subtitles_styled.py
Generate a beautifully styled Advanced SubStation Alpha (.ass) subtitle file with custom highlight tags.
"""

import argparse
import json
import sys

# Default ASS header template
ASS_TEMPLATE = """[Script Info]
; Script generated by subtitles_styled.py
ScriptType: v4.00+
PlayResX: {res_x}
PlayResY: {res_y}
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font_name},{font_size},{primary_color},{secondary_color},{outline_color},{back_color},{bold},{italic},0,0,100,100,0,0,1,{outline},{shadow},{alignment},10,10,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

def format_ass_time(seconds):
    """Convert float seconds to ASS timestamp format (H:MM:SS.cs)"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    cs = int(round((seconds % 1) * 100))
    if cs == 100:
        s += 1
        cs = 0
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"

def convert_hex_to_ass_color(hex_color, include_alpha=True):
    """
    Convert standard #RRGGBB or #RRGGBBAA hex color to ASS format &HAABBGGRR or &HBBGGRR.
    ASS uses Alpha-Blue-Green-Red hex representation.
    Note that ASS Alpha is inverted (00 = fully opaque, FF = fully transparent).
    """
    hex_color = hex_color.lstrip('#')
    
    if len(hex_color) == 6:
        r, g, b = hex_color[0:2], hex_color[2:4], hex_color[4:6]
        a = "00"
    elif len(hex_color) == 8:
        r, g, b, a = hex_color[0:2], hex_color[2:4], hex_color[4:6], hex_color[6:8]
        # Invert alpha for ASS (00 = opaque, FF = transparent)
        a_val = 255 - int(a, 16)
        a = f"{a_val:02x}"
    else:
        raise ValueError(f"Invalid hex color format: {hex_color}. Must be #RRGGBB or #RRGGBBAA.")
        
    if include_alpha:
        return f"&H{a}{b}{g}{r}"
    else:
        return f"&H{b}{g}{r}"

def generate_ass(words_data, output_path, config):
    """
    Compile ASS file from timed words list.
    words_data is a list of dicts: {"start": float, "end": float, "text": str, "highlight": bool}
    """
    primary_color = convert_hex_to_ass_color(config["primary_color"])
    secondary_color = convert_hex_to_ass_color(config["secondary_color"])
    outline_color = convert_hex_to_ass_color(config["outline_color"])
    back_color = convert_hex_to_ass_color(config["back_color"])
    highlight_color_ass = convert_hex_to_ass_color(config["highlight_color"], include_alpha=False)
    
    header = ASS_TEMPLATE.format(
        res_x=config["res_x"],
        res_y=config["res_y"],
        font_name=config["font_name"],
        font_size=config["font_size"],
        primary_color=primary_color,
        secondary_color=secondary_color,
        outline_color=outline_color,
        back_color=back_color,
        bold=1 if config["bold"] else 0,
        italic=1 if config["italic"] else 0,
        outline=config["outline"],
        shadow=config["shadow"],
        alignment=config["alignment"],
        margin_v=config["margin_v"]
    )
    
    dialogues = []
    for item in words_data:
        start_t = format_ass_time(item["start"])
        end_t = format_ass_time(item["end"])
        text = item["text"]
        
        # Inject highlight code if specified
        if item.get("highlight", False):
            text = f"{{\\c{highlight_color_ass}&}}{text}{{\\c}}"
            
        dialogues.append(
            f"Dialogue: 0,{start_t},{end_t},Default,,0000,0000,0000,,{text}"
        )
        
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("\n".join(dialogues))
        f.write("\n")
        
    print(f"Generated ASS subtitle file: {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Generate beautifully styled ASS subtitles.")
    parser.add_argument("--input", required=True, help="Path to input JSON file containing timed words.")
    parser.add_argument("--output", required=True, help="Path to save output ASS file.")
    parser.add_argument("--font", default="Arial", help="Font family name.")
    parser.add_argument("--size", type=int, default=32, help="Font size in pixels.")
    parser.add_argument("--color", default="#FFFFFF", help="Primary font color (#RRGGBB).")
    parser.add_argument("--highlight-color", default="#00FFFF", help="Highlight font color (#RRGGBB).")
    parser.add_argument("--outline-color", default="#000000", help="Outline/border color (#RRGGBB).")
    parser.add_argument("--outline", type=int, default=3, help="Outline thickness in pixels.")
    parser.add_argument("--shadow", type=int, default=1, help="Shadow offset in pixels.")
    parser.add_argument("--alignment", type=int, default=2, help="ASS Alignment code (2=bottom-center, 6=top-center, etc).")
    parser.add_argument("--margin-v", type=int, default=15, help="Vertical margin in pixels.")
    
    args = parser.parse_args()
    
    config = {
        "res_x": 1920,
        "res_y": 1080,
        "font_name": args.font,
        "font_size": args.size,
        "primary_color": args.color,
        "secondary_color": "#00000000",
        "outline_color": args.outline_color,
        "back_color": "#00000000",
        "highlight_color": args.highlight_color,
        "bold": True,
        "italic": False,
        "outline": args.outline,
        "shadow": args.shadow,
        "alignment": args.alignment,
        "margin_v": args.margin_v
    }
    
    try:
        with open(args.input, "r", encoding="utf-8") as f:
            words_data = json.load(f)
    except Exception as e:
        print(f"Error loading JSON input: {e}", file=sys.stderr)
        sys.exit(1)
        
    generate_ass(words_data, args.output, config)

if __name__ == "__main__":
    main()
